export default {
  TOGGLE_LOADING: "TOGGLE_LOADING",
  GET_ALL_CONTACTS_START: "GET_ALL_CONTACTS_START",
  SET_SELECTED_CONTACT: "SET_SELECTED_CONTACT",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  FILTTER_CONTACTS: "FILTTER_CONTACTS",
};
